# Generated by Django 3.0.5 on 2020-07-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='message',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='name',
        ),
    ]
