# Generated by Django 3.0.5 on 2020-07-24 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('leads', '0004_auto_20200721_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='accounts.User'),
        ),
    ]
